version: '3'

services:
    swoole:
        build: ./docker/swoole
        ports:
            - 9501:9501
        working_dir: /app
        volumes:
            - ./:/app
        restart: always
    php:
        container_name: yii-php
        build: ./docker/swoole
        working_dir: /app
        volumes:
            - ./:/app
        entrypoint: tail -f /dev/null
    nginx:
        image: nginx:alpine
        container_name: yii-nginx
        ports:
            - 8080:80
            - 8081:81
        volumes:
            - ./:/app
            - ./data/nginx/:/etc/nginx/conf.d/
        depends_on:
            - php
        restart: always
